jee-configuration/src/main/java/com/gitlab/thofis/cleangreetings/GreetingBean.java
package com.gitlab.thofis.cleangreetings;

import com.gitlab.thofis.cleangreetings.model.Greeting;
import com.gitlab.thofis.cleangreetings.model.Salutation;
import com.gitlab.thofis.cleangreetings.ports.in.CreateGreeting;
import com.gitlab.thofis.cleangreetings.ports.in.LoadGreetings;
import com.gitlab.thofis.cleangreetings.usecases.CreateGreetingUsecase;
import com.gitlab.thofis.cleangreetings.usecases.LoadGreetingsUsecase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Collection;

@Named
@RequestScoped
public class GreetingBean implements Serializable {

  private static final Logger log = LoggerFactory.getLogger(GreetingBean.class);
  @Inject
  JpaGreetingRepository greetingRepository;
  private CreateGreeting createGreeting;
  private LoadGreetings loadGreetings;
  private String enteredName;
  private Salutation selectedSalutation;

  @PostConstruct
  public void init() {
    createGreeting = new CreateGreetingUsecase(greetingRepository);
    loadGreetings = new LoadGreetingsUsecase(greetingRepository);

    selectedSalutation = Salutation.HELLO;
    enteredName = "World";
  }

  public String createGreeting() {
    Greeting greeting = createGreeting.execute(selectedSalutation, enteredName);
    log.info("create greeting: {}", greeting);
    return "index.xhtml";
  }

  public Collection<? extends Greeting> getGreetings() {
    return loadGreetings.execute();
  }

  public Salutation[] getSalutations() {
    return Salutation.values();
  }

  public String getEnteredName() {
    return enteredName;
  }

  public void setEnteredName(String enteredName) {
    this.enteredName = enteredName;
  }

  public Salutation getSelectedSalutation() {
    return selectedSalutation;
  }

  public void setSelectedSalutation(Salutation selectedSalutation) {
    this.selectedSalutation = selectedSalutation;
  }
}

jee-configuration/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>My first application</title>
</h:head>
<h:body>
    <h:form id="greeting">
        <h:selectOneMenu value="#{greetingBean.selectedSalutation}">
            <f:selectItems value="#{greetingBean.salutations}" var="salutation"
                           itemValue="#{salutation}" itemLabel="#{salutation.text}"/>
        </h:selectOneMenu>
        <h:inputText value="#{greetingBean.enteredName}" label="Name: "/>
        <h:commandButton action="#{greetingBean.createGreeting()}" value="Create"/>
    </h:form>
    <hr/>
    <ul>
        <ui:repeat value="#{greetingBean.greetings}" var="greeting">
            <li>
                <h:outputText value="#{greeting}"/>
            </li>
        </ui:repeat>
    </ul>
</h:body>
</html>